In [1]:
import pandas as pd
import numpy as np
import random

from recsys_utils import recsys_load_training_df, recsys_evaluate, recsys_cv_split_single

df_data = recsys_load_training_df('../Data/training_sample.tsv')
#df_data = recsys_load_training_df('../Data/training_sample_by_tweet.tsv')

In [2]:
df_data.head(2)

,text_tokens,hashtags,tweet_id,present_media,present_links,present_domains,tweet_type,language,tweet_timestamp,engaged_with_user_id,...,engaging_user_id,engaging_user_follower_count,engaging_user_following_count,engaging_user_is_verified,engaging_user_account_creation,engaged_follows_engaging,reply_timestamp,retweet_timestamp,retweet_with_comment_timestamp,like_timestamp
0,"[101, 100, 10247, 120, 122, 60987, 138, 20057,...",NaN,3394E18DD0BDBE140AE850DC006BDC76,[Photo],[DC409D513A7C1E6419DB8F0CD45229BF],[927237AFF58CF6F8D754E1E1A275E4FD],TopLevel,D3164C7FBCF2565DDF915B1B3AEFB1DC,2020-02-09 13:20:00,C9C2E6983151093663204A8651D47D3E,...,74700241E1B5E0E7C54DDB6BF783FE6F,158,96,False,2012-05-05 19:29:00,False,NaT,NaT,NaT,NaT
1,"[101, 23962, 10238, 81387, 10229, 100, 102]",NaN,2C08EF332B855FF78CEEF391DBFE9FC7,NaN,NaN,NaN,Quote,06D61DCBBE938971E1EA0C38BD9B5446,2020-02-09 15:30:20,EA2A0D530B930CF8082C54CCC28C8C3C,...,747005A28E21F329ACEA1B435FFD2238,10965,7503,False,2011-07-14 00:39:12,True,NaT,NaT,NaT,NaT

In [3]:
def recommender_train_predict(df_train, df_test):
    # TODO: Train based on df_train and predict for df_test
    for idx, row in df_test.iterrows():
        pred_reply = random.random()
        pred_retweet = random.random()
        pred_retweet_wc = random.random()
        pred_like = 1.0 if not pd.isnull(row['like_timestamp']) else 0.0
        
        yield pred_reply, pred_retweet, pred_retweet_wc, pred_like

#df_results = recsys_evaluate(df_data, recommender_train_predict, ['tweetid', 'time'])
df_results = recsys_evaluate(df_data, recommender_train_predict, 'all')
df_results

Run RecSys recommender evaluation:
CPUs: 16
> cv-split (single_random)
> cv-split (tweetid)
> cv-split (userid)
> cv-split (time)
> cv-split (single_time)

                    like (CTR)  like (PRAUC)  like (RCE)  reply (CTR)  \
split_type    agg
single_random max     0.435845           1.0       100.0     0.023749
              mean    0.435845           1.0       100.0     0.023749
              min     0.435845           1.0       100.0     0.023749
single_time   max     0.467234           1.0       100.0     0.025546
              mean    0.467234           1.0       100.0     0.025546
              min     0.467234           1.0       100.0     0.025546
time          max     0.467234           1.0       100.0     0.028878
              mean    0.441725           1.0       100.0     0.024769
              min     0.423547           1.0       100.0     0.020733
tweetid       max     0.458165           1.0       100.0     0.031261
              mean    0.441980           1.0       100.0     0.025336
              min     0.425210           1.0       100.0     0.021248
userid        max     0.506088           1.0       100.0     0.030394
              mean    0.441089           1.0       100.0     0.025376
              min     0.412096           1.0       100.0     0.019162

                    reply (PRAUC)  reply (RCE)  retweet (CTR)  \
split_type    agg
single_random max        0.027303  -781.577614       0.120793
              mean       0.027303  -781.577614       0.120793
              min        0.027303  -781.577614       0.120793
single_time   max        0.029451  -716.823001       0.114032
              mean       0.029451  -716.823001       0.114032
              min        0.029451  -716.823001       0.114032
time          max        0.030090  -675.772255       0.126620
              mean       0.025184  -773.178082       0.117216
              min        0.020125  -883.685663       0.109219
tweetid       max        0.038649  -620.082257       0.129217
              mean       0.027031  -751.043993       0.117575
              min        0.020009  -866.657282       0.105210
userid        max        0.036868  -629.201588       0.153918
              mean       0.027267  -759.575306       0.116994
              min        0.018140  -948.070776       0.092827

                    retweet (PRAUC)  retweet (RCE)  retweet_wc (CTR)  \
split_type    agg
single_random max          0.121231    -170.445064          0.008372
              mean         0.121231    -170.445064          0.008372
              min          0.121231    -170.445064          0.008372
single_time   max          0.110980    -181.574227          0.007034
              mean         0.110980    -181.574227          0.007034
              min          0.110980    -181.574227          0.007034
time          max          0.133453    -156.987608          0.011477
              mean         0.118952    -173.241208          0.007220
              min          0.110645    -188.942647          0.005183
tweetid       max          0.124498    -163.262640          0.011134
              mean         0.117772    -176.431186          0.007404
              min          0.107547    -193.098103          0.004370
userid        max          0.160752    -126.646660          0.011692
              mean         0.119708    -177.655208          0.007418
              min          0.094140    -214.708664          0.005086

                    retweet_wc (PRAUC)  retweet_wc (RCE)
split_type    agg
single_random max             0.008608      -1981.197724
              mean            0.008608      -1981.197724
              min             0.008608      -1981.197724
single_time   max             0.005960      -2299.588673
              mean            0.005960      -2299.588673
              min             0.005960      -2299.588673
time          max             0.011396      -1402.532176
              mean            0.008269      -2300.828372
              min             0.005080      -2960.050788
tweetid       max             0.011964      -1509.056916
              mean            0.008220      -2347.699622
              min             0.003647      -3434.438829
userid        max             0.011550      -1489.263147
              mean            0.007230      -2331.216278
              min             0.005299      -3094.449899